import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";


 
const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={mulish.className}>
      <body className={inter.className}>
        <Navbar></Navbar>
        
        {children}
        </body>
    </html>
  );
}
